# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HDHUD' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HDHUD
  pod 'SnapKit', '~> 5.0'
  pod 'DDUtils/ui', '~> 5.0'
#  pod 'Kingfisher'
end
